import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { Key } from '@lichess-org/chessground/types';
import { Chess } from 'chess.js';

// Generated by `wasm-pack build rules-wasm --target web --out-dir
// chessground-board/src/wasm` - see rules-wasm/README.md. This import
// only resolves after that command has been run at least once.
import init, { Game } from '../wasm/rules_wasm.js';

type PromotionRole = 'q' | 'r' | 'b' | 'n';

interface StateSnapshot {
  fen: string;
  turn: 'white' | 'black';
  check: boolean;
  gameOver: boolean;
  checkmate: boolean;
  stalemate: boolean;
  insufficientMaterial: boolean;
  dests: [string, string[]][];
  lastMove: [string, string] | null | undefined;
}

interface NotationMove {
  from: string;
  to: string;
  promotion?: string;
}

// Bandingin posisi lewat 3 field pertama FEN (papan, giliran, castling) - field en-passant &
// clock sengaja diabaikan karena beda library bisa nulisnya beda padahal posisinya sama.
const fenKey = (fen: string) => fen.split(' ').slice(0, 3).join(' ');

const resultTag = (s: StateSnapshot) => (s.checkmate ? (s.turn === 'white' ? '0-1' : '1-0') : '1/2-1/2');

// Cari urutan move terpendek (maks. 2 ply) dari posisi `from` ke `targetFen`. Dipakai buat nambal
// langkah yang kelewat pas WebSocket putus: papan dikunci saat offline, jadi realistisnya cuma
// 1 langkah lawan yang bisa kelewat (2 ply kalau langkah kita sendiri sempat terkirim pas putus).
// Dibatasi 2 ply karena chess.js lambat - 3 ply itu ~27rb node di main thread HP.
function findGap(from: Chess, targetFen: string, maxPly = 2): NotationMove[] | null {
  const targetKey = fenKey(targetFen);
  const sameTurn = from.turn() === targetFen.split(' ')[1];
  const scratch = new Chess(from.fen());
  const path: NotationMove[] = [];
  const search = (left: number): boolean => {
    if (left === 0) return fenKey(scratch.fen()) === targetKey;
    for (const m of scratch.moves({ verbose: true })) {
      const step: NotationMove = { from: m.from, to: m.to, ...(m.promotion ? { promotion: m.promotion } : {}) };
      scratch.move(step);
      path.push(step);
      if (search(left - 1)) return true;
      path.pop();
      scratch.undo();
    }
    return false;
  };
  for (let ply = 1; ply <= maxPly; ply++) {
    if ((ply % 2 === 0) !== sameTurn) continue; // paritas ply harus cocok dengan giliran target
    if (search(ply)) return path;
  }
  return null;
}

export interface ChessGameState {
  /** False until the wasm module has loaded and the game is playable. */
  ready: boolean;
  /** Full FEN (board + turn + castling + ep), undefined until ready. */
  fen: string | undefined;
  /** Just the board-placement field of `fen` - what Chessground's own
   * `config.fen` expects. */
  boardFen: string | undefined;
  turn: 'white' | 'black' | undefined;
  /** Ready to hand straight to Chessground's `movable.dests`. */
  dests: Map<Key, Key[]>;
  check: boolean;
  gameOver: boolean;
  checkmate: boolean;
  stalemate: boolean;
  insufficientMaterial: boolean;
  lastMove: [Key, Key] | undefined;
  /** Returns false (and leaves state untouched) if the move is illegal -
   * shouldn't normally happen since Chessground only offers squares
   * already in `dests`, but guards stale-dests edge cases safely. */
  tryMove: (orig: Key, dest: Key, promotion?: PromotionRole) => boolean;
  reset: () => void;
  /** Replaces the current game with the position from `fen`. Used to
   * resync with the server's authoritative state (e.g. after a
   * WebSocket reconnect, in case moves happened while disconnected).
   * Silently does nothing if `fen` is invalid or wasm isn't ready yet.
   * `moves` (opsional) = daftar langkah lengkap dari server dalam UCI ("e2e4", "e7e8q"); kalau
   * ada dan cocok dengan `fen`, notasi dibangun ulang utuh dari situ. */
  loadFen: (fen: string, moves?: string[]) => void;
  /** Non-null kalau rules engine (wasm) gagal dimuat. */
  error: string | null;
  /** Notasi SAN tiap ply, mis. ['e4','e5','Nf3',...]. Dijaga instance chess.js TERPISAH yang
   * cuma meniru move yang sudah lolos WASM (disambiguasi, +/#, O-O tanpa nulis generator SAN
   * sendiri) - rules-wasm tetap satu-satunya sumber legalitas. Waktu `loadFen` (resync
   * FriendRoom) urutan pemulihannya: (1) `moves` dari server kalau ada, (2) posisi sama dengan
   * yang sudah dicatat -> dibiarkan, (3) selisih <= 2 ply dicari lalu ditambal, (4) baru
   * di-reset dari posisi itu (daftar langkah kosong). Local Pass & Play gak pernah kena. */
  moveHistory: string[];
  /** PGN siap-download buat game saat ini (header standar chess.js + notasi di atas). */
  pgn: string;
}

// Module-level so every component sharing this hook waits on the same
// load instead of re-fetching the .wasm file per mount.
let wasmReady: Promise<unknown> | null = null;
function loadWasm() {
  // Kalau gagal (mis. .wasm gak ke-fetch), reset supaya mount berikutnya bisa
  // coba lagi - bukan nyangkut selamanya di promise yang udah rejected.
  if (!wasmReady) {
    wasmReady = init().catch((e) => {
      wasmReady = null;
      throw e;
    });
  }
  return wasmReady;
}

export function useChessGame(): ChessGameState {
  const gameRef = useRef<Game | null>(null);
  const [snapshot, setSnapshot] = useState<StateSnapshot | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Lazy: `useRef(new Chess())` akan membuat instance baru (dibuang) di SETIAP render.
  const [initialNotation] = useState(() => new Chess());
  const notationRef = useRef(initialNotation);
  const [notation, setNotation] = useState<{ history: string[]; pgn: string }>({ history: [], pgn: '' });

  useEffect(() => {
    let cancelled = false;
    loadWasm().then(() => {
      if (cancelled) return;
      const game = new Game();
      gameRef.current = game;
      setSnapshot(game.state() as StateSnapshot);
    }).catch(() => {
      if (!cancelled) setError('Gagal memuat rules engine - coba muat ulang halaman.');
    });
    return () => {
      cancelled = true;
    };
  }, []);

  const tryMove = useCallback((orig: Key, dest: Key, promotion?: PromotionRole) => {
    const game = gameRef.current;
    if (!game) return false;
    try {
      const next = game.applyMove(orig, dest, promotion) as StateSnapshot;
      setSnapshot(next);
      // Niru move yang sama ke chess.js buat notasi. Kalau ini gagal (harusnya gak pernah,
      // karena WASM sudah bilang legal), diam-diam skip - notasi cuma nice-to-have, gak
      // boleh sampai bikin move yang beneran berhasil kelihatan gagal.
      try {
        // WASM auto-queen kalau promotion kosong; chess.js wajib dikasih, jadi samakan ('q' diabaikan utk move biasa).
        notationRef.current.move({ from: orig, to: dest, promotion: promotion ?? 'q' });
        if (next.gameOver) notationRef.current.header('Result', resultTag(next));
        setNotation({ history: notationRef.current.history(), pgn: notationRef.current.pgn() });
      } catch {
        // desync notasi - papan tetap benar dari WASM, cuma notasi yang ketinggalan
      }
      return true;
    } catch {
      return false;
    }
  }, []);

  const reset = useCallback(() => {
    if (!gameRef.current) return; // wasm not loaded yet, nothing to reset
    const game = new Game();
    gameRef.current = game;
    setSnapshot(game.state() as StateSnapshot);
    notationRef.current = new Chess();
    setNotation({ history: [], pgn: '' });
  }, []);

  const loadFen = useCallback((fen: string, moves?: string[]) => {
    if (!gameRef.current) return; // wasm not loaded yet
    let snap: StateSnapshot;
    try {
      const game = Game.fromFen(fen);
      gameRef.current = game;
      snap = game.state() as StateSnapshot;
      setSnapshot(snap);
    } catch {
      // FEN gak valid buat WASM - biarin semuanya (termasuk notasi) apa adanya
      return;
    }

    const target = fenKey(fen);
    const adopt = (chess: Chess) => {
      if (snap.gameOver) chess.header('Result', resultTag(snap));
      notationRef.current = chess;
      setNotation({ history: chess.history(), pgn: chess.pgn() });
    };

    // 1) Server ngasih daftar langkah lengkap -> paling akurat, bangun ulang dari awal.
    if (moves && moves.length > 0) {
      try {
        const rebuilt = new Chess();
        for (const uci of moves) {
          rebuilt.move({ from: uci.slice(0, 2), to: uci.slice(2, 4), promotion: uci.length > 4 ? uci[4] : 'q' });
        }
        if (fenKey(rebuilt.fen()) === target) {
          adopt(rebuilt);
          return;
        }
      } catch {
        // daftar dari server gak bisa diputar ulang - lanjut ke cara berikutnya
      }
    }

    // 2) Posisinya sama dengan yang sudah kita catat -> gak ada langkah yang kelewat.
    if (fenKey(notationRef.current.fen()) === target) {
      adopt(notationRef.current);
      return;
    }

    // 3) Ada selisih kecil (mis. 1 langkah lawan pas offline) -> cari dan tambal.
    try {
      const gap = findGap(notationRef.current, fen);
      if (gap) {
        for (const m of gap) notationRef.current.move(m);
        adopt(notationRef.current);
        return;
      }
    } catch {
      // chess.js gak cocok - jatuh ke reset
    }

    // 4) Gak bisa dipulihkan -> mulai dari posisi ini.
    try {
      const fresh = new Chess();
      fresh.load(fen);
      adopt(fresh);
    } catch {
      notationRef.current = new Chess();
      setNotation({ history: [], pgn: '' });
    }
  }, []);

  const dests = useMemo(() => {
    if (!snapshot) return new Map<Key, Key[]>();
    return new Map(snapshot.dests as [Key, Key[]][]);
  }, [snapshot]);

  return {
    ready: snapshot !== null,
    fen: snapshot?.fen,
    boardFen: snapshot?.fen.split(' ')[0],
    turn: snapshot?.turn,
    dests,
    check: snapshot?.check ?? false,
    gameOver: snapshot?.gameOver ?? false,
    checkmate: snapshot?.checkmate ?? false,
    stalemate: snapshot?.stalemate ?? false,
    insufficientMaterial: snapshot?.insufficientMaterial ?? false,
    lastMove: snapshot?.lastMove ? (snapshot.lastMove as [Key, Key]) : undefined,
    tryMove,
    reset,
    loadFen,
    error,
    moveHistory: notation.history,
    pgn: notation.pgn,
  };
}
