import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { Key } from '@lichess-org/chessground/types';

// Generated by `wasm-pack build rules-wasm --target web --out-dir
// chessground-board/src/wasm` - see rules-wasm/README.md. This import
// only resolves after that command has been run at least once.
import init, { Game } from '../wasm/rules_wasm.js';

type PromotionRole = 'q' | 'r' | 'b' | 'n';

interface StateSnapshot {
  fen: string;
  turn: 'white' | 'black';
  check: boolean;
  gameOver: boolean;
  checkmate: boolean;
  stalemate: boolean;
  insufficientMaterial: boolean;
  dests: [string, string[]][];
  lastMove: [string, string] | null | undefined;
}

export interface ChessGameState {
  /** False until the wasm module has loaded and the game is playable. */
  ready: boolean;
  /** Full FEN (board + turn + castling + ep), undefined until ready. */
  fen: string | undefined;
  /** Just the board-placement field of `fen` - what Chessground's own
   * `config.fen` expects. */
  boardFen: string | undefined;
  turn: 'white' | 'black' | undefined;
  /** Ready to hand straight to Chessground's `movable.dests`. */
  dests: Map<Key, Key[]>;
  check: boolean;
  gameOver: boolean;
  checkmate: boolean;
  stalemate: boolean;
  insufficientMaterial: boolean;
  lastMove: [Key, Key] | undefined;
  /** Returns false (and leaves state untouched) if the move is illegal -
   * shouldn't normally happen since Chessground only offers squares
   * already in `dests`, but guards stale-dests edge cases safely. */
  tryMove: (orig: Key, dest: Key, promotion?: PromotionRole) => boolean;
  reset: () => void;
}

// Module-level so every component sharing this hook waits on the same
// load instead of re-fetching the .wasm file per mount.
let wasmReady: Promise<unknown> | null = null;
function loadWasm() {
  if (!wasmReady) wasmReady = init();
  return wasmReady;
}

export function useChessGame(): ChessGameState {
  const gameRef = useRef<Game | null>(null);
  const [snapshot, setSnapshot] = useState<StateSnapshot | null>(null);

  useEffect(() => {
    let cancelled = false;
    loadWasm().then(() => {
      if (cancelled) return;
      const game = new Game();
      gameRef.current = game;
      setSnapshot(game.state() as StateSnapshot);
    });
    return () => {
      cancelled = true;
    };
  }, []);

  const tryMove = useCallback((orig: Key, dest: Key, promotion?: PromotionRole) => {
    const game = gameRef.current;
    if (!game) return false;
    try {
      const next = game.applyMove(orig, dest, promotion) as StateSnapshot;
      setSnapshot(next);
      return true;
    } catch {
      return false;
    }
  }, []);

  const reset = useCallback(() => {
    if (!gameRef.current) return; // wasm not loaded yet, nothing to reset
    const game = new Game();
    gameRef.current = game;
    setSnapshot(game.state() as StateSnapshot);
  }, []);

  const dests = useMemo(() => {
    if (!snapshot) return new Map<Key, Key[]>();
    return new Map(snapshot.dests as [Key, Key[]][]);
  }, [snapshot]);

  return {
    ready: snapshot !== null,
    fen: snapshot?.fen,
    boardFen: snapshot?.fen.split(' ')[0],
    turn: snapshot?.turn,
    dests,
    check: snapshot?.check ?? false,
    gameOver: snapshot?.gameOver ?? false,
    checkmate: snapshot?.checkmate ?? false,
    stalemate: snapshot?.stalemate ?? false,
    insufficientMaterial: snapshot?.insufficientMaterial ?? false,
    lastMove: snapshot?.lastMove ? (snapshot.lastMove as [Key, Key]) : undefined,
    tryMove,
    reset,
  };
}
